### ISSUE TITLE
Add capability of rerunFailingTestsCount in parallel as an optional parameter 

### ISSUE THREAD

**Issue by Srinivasaraor** [trivago/cucable-plugin#113]
This is a Request for new feature :Add capability of rerunFailingTestsCount in parallel 

I am big fan of Cucable and Clucumber plugin.
And recently I have been working on incorporating rerunning of failed tests as optional parameter in our frame work , I have gone through multiple options and below is the summary and drawbacks

**1.	MVN: Failsafe and Surefire : -Dsurefire.rerunFailingTestsCount=2**
This inbuilt option is working fine when we run test in sequential , it is rerunning failed test desired number of times and giving us good report on flaky tests. But failing with cucable parallel execution.
**2.	Get count of failed test in rerun.txt and execute with failsafe :**
We could able to rerun failed test one time after parallel execution but unable to run desired number of times and no proper reporting on flaky tests.
**3.	@ExtendedCucubmeroptions:**
As we know with extended cucumber options we could able to rerun the failed tests desired number of times with the option reruncount, downside is ExtendCucumber option  is not working with Cucable plugin.

I would like to see rerunning failed test count as inbuilt optional parameter in cucable plugin . This is a great feature which adds the value to plugin. Please let me know your thoughts .

**Comment by laxersaz** [comment]
Cucable is not a test runner but only splits features and scenarios into parallelizable parts. So implementing rerun functionality is not a matter of Cucable but your test framework/Maven setup.
Sorry to disappoint you here.

In fact, we use a custom framework plugin to gather specific scenarios based on their exception in order to rerun them in a separate failsafe livecycle.
