### ISSUE TITLE
Not a directory 

### ISSUE THREAD

**Issue by Hanumanthap24** [trivago/cucable-plugin#161]
Hi,

When I run my test in IntelliJ using CucableJavaTemplate provided in the example, I am getting the below error .Could you please advise?

java.lang.IllegalArgumentException: Not a file or directory: C:\Users\MyName\Downloads\Parallel\target\parallel\features\[CUCABLE:FEATURE].feature

Thanks,
Hanumantha

**Comment by laxersaz** [comment]
This is a template, not a runner. Are you trying to run the template without running Cucable? Please give me some more details.

**Comment by Hanumanthap24** [comment]
Did not understand what do you mean by running cucable.I have placed my feature files exactly at the location Project/target/parallel/features. and Clicked on Run .You have any YouTube video,that helps.

**Comment by laxersaz** [comment]
Have you tried running the example project? Because this shows you exactly how it works.

Placing your feature files in target is NOT correct. This is something that Cucable does when you invoke it. Also clicking on `run` in your IDE will not do anything since Cucable is a Maven plugin that needs to be __run__ via Maven.

**Comment by Hanumanthap24** [comment]
Thanks for the help.I am now able to run my tests.
