### ISSUE TITLE
Only one Scenario Outlines displayed in Report

### ISSUE THREAD

**Issue by s1apped** [trivago/cucable-plugin#38]
Hi @laxersaz ,

Scenario Outline in 1.3 works as expected. Thank you.
Now there is a problem with displaying scenarios in report. Looks like only last one is displayed since each of them has the same name so they are being overwritten.

**Comment by laxersaz** [comment]
Which reporting do you use? And do you have an example where that happens?

**Comment by s1apped** [comment]
I'm using Serenity. It happens for every scenario outline.
Below screens shows report of scenario outline executions:
 - without Cucable

![image](https://user-images.githubusercontent.com/32245059/34269322-1ca42a84-e684-11e7-9123-ac4297369882.png)
as you can see scenario outline has 212 examples and one you go inside you can see every single example.


- with Cucable
![image](https://user-images.githubusercontent.com/32245059/34269403-71ea6b34-e684-11e7-88ca-bd7bf4d315a4.png)
looks like a standard scenario

**Comment by laxersaz** [comment]
I will investigate this further. Thanks for reporting this!

**Comment by laxersaz** [comment]
Hello, I found out that this is a problem with Serenity's reporting:

In this [Serenity blog article](https://johnfergusonsmart.com/running-parallel-tests-serenity-bdd-cucumber/), it says:

> Unfortunately, each scenario in scenario outlines are also executed in parallel, which messes with Serenity’s reporting.

The thing is that Cucable generated single Scenarios from outlines because this allows for much finer grained parallel runs. If Cucable had an option to keep outlines as they are (like cucumber-jvm-parallel-plugin's `parallelScheme`, this would solve it but then you would not get any gain from this since the individual outline examples could not be parallelized. This would contradict Cucable's purpose.

Another way to solve this would be to use a different reporting library like my [Cluecumber](https://github.com/trivago/cluecumber-report-plugin) project.

**Comment by laxersaz** [comment]
Hi @s1apped,

I just had an idea that might be able to solve this. I wonder what would happen if Cucable generated Scenario Outlines not as single Scenarios but individual Scenario Outlines with one example each. It might be that Serenity reporting would combine them to a single Scenario Outline report like before.

Could you check that since I don't have Serenity set up here?

Merry Christmas,
Benjamin

**Comment by s1apped** [comment]
Hi @laxersaz ,

Sorry for late response. It doesn't work.  I tried with 2 Scenario Outlines with one example each and same Scenario name. Report was generated only with 2nd scenario. Looks like 1st one was overwritten.
I will try to play with Cluecumber.

Happy New Year,
Matt

**Comment by laxersaz** [comment]
Hi,

thanks for letting me know. I will try to find out more about how Serenity ticks. 

Happy New Year, 
Benjamin

**Comment by vikramvi** [comment]
@s1apped can you please share your pom.xml, I am curious to know how you're using Serenity with cucable-plugin ?

**Comment by laxersaz** [comment]
@s1apped, I created an issue in Cluecumber Reporting. Maybe it is possible to combine Scenario Outline Examples in the report again even if they were split into separate Scenarios by Cucable.

https://github.com/trivago/cluecumber-report-plugin/issues/18

**Comment by Avionerman** [comment]
Is there any solution for this issue?
It is really important..

I am having a feature file with a Scenario Outline (10 or 11 examples) and only the last one is being reported. Is there any way to "append" in the end of each execution the json content into a summarised json file?
I mean that is there a way to take 10 small json files and add them in the summarised json file?

Thanks in advance!

**Comment by laxersaz** [comment]
Sorry to say but as mentioned before this is not related to Cucable but your test framework and how it handles the JSON generation. We use a custom Cucumber based framework which appends to existing JSON files (this is the Cucumber default behavior as well).

**Comment by Avionerman** [comment]
Nice. This answer was clear. Thanks!

Tip: for those who use Cucumber they can insert a simple @Tag and above it the "Scenario Outline".
The plug in will read it as one "object". Hope I helped.
Take care  :)
