### ISSUE TITLE
Provision of retry failed scenarios in cucable template

### ISSUE THREAD

**Issue by jdoriyastpl** [trivago/cucable-plugin#52]

**Comment by jdoriyastpl** [comment]
Hi @laxersaz ,

Can you please guide, how to implement retry failed scenarios mechanism with cucable template?

Thanks
jitin

**Comment by laxersaz** [comment]
This is a question that does not really belong to Cucable but to Cucumber itself.
We solved it by having a second runner (not a template) that takes scenarios from a rerun.txt file and invoking this one in a second failsafe execution block.

**Comment by jdoriyastpl** [comment]
@laxersaz  Thanks for suggestion

**Comment by rahulbommanaboina** [comment]
@laxersaz : Is there a way we can add another column in the html reports as "Retry" , we would like to know the count it tried for the scenarios , apart from this it will be good if Retry configuration is available in the same plugin , rather than using another runner file. Please suggest.
![capture](https://user-images.githubusercontent.com/29060552/53951914-90157000-40f5-11e9-937f-b6c023e00afb.PNG)

**Comment by laxersaz** [comment]
As long as this is reflected in the resulting JSON files, this could potentially be displayed by Cluecumber. Adding custom columns is not possible (at least not in the current state of Cluecumber).

**Comment by rahulbommanaboina** [comment]
Ya thank you @laxersaz
