### ISSUE TITLE
Forking creating issues with users

### ISSUE THREAD

**Issue by deepthi-ravindra** [trivago/cucable-plugin#56]
Hello,

We are having issues when running multiple scenarios in parallel with a set of users. We use a csv file to store and pick users and this is not being shared as each test is being forked and isolated.

So multiple users are having to use up the same users at same time and creating issues.

Any help appreciated!

**Comment by laxersaz** [comment]
This is not a Cucable issue but sounds more like a test design problem in your case. In general, your scenarios should be independent of each other and runnable on their own. In your case they aren't since they all depend on a single shared data source. Without more knowledge of your use case I cannot really help here, I'm afraid.
Maybe running the tests with separated forks (and separated JVMs) is not the right way in your case. Check out the other Failsafe options because it is also possible to run inside the same JVM but with multiple threads ("parallel" option).
