### ISSUE TITLE
How to bring up shared embedded environment?

### ISSUE THREAD

**Issue by amitavaghosh1981** [trivago/cucable-plugin#89]
We need to bring shared environment before executing all the feature files. Earlier we kept this in the cucumber starter file and now since all the files have same copy of cucumber starter we we are not able to bring up single instance of shared embedded server. We nee some clue how this can be possible.

**Comment by laxersaz** [comment]
Basically, if you need any shared environment for tests, this should be spun up before your tests run. 
Without more details from your side I cannot judge what have to be done here (also this request is not something related to Cucable as far as I can see).

**Comment by laxersaz** [comment]
In this case, you either have to spin up the test environment before running those tests (using a CI pipeline, a separate Maven goal or profile, a shell script, Docker etc.) or check within your @BeforeClass if your environment is already running.
There is no way for Cucable to determine how to deal with this scenario since its only concern is splitting up runners and features but not running the resulting test classes.
