### ISSUE TITLE
[Q] Cucable with cucumber 4?

### ISSUE THREAD

**Issue by abhishek8908** [trivago/cucable-plugin#95]
Cucumber version 4 already supports the parallel run. How this plugin can help people who are using cucumber version 4?

**Comment by laxersaz** [comment]
It has more options than the native Cucumber 4 parallel capabilities:
- It supports running single scenarios in parallel with JUnit
- It supports splitting scenarios and attaching them to a fixed number of runners
- You don't need any test framework changes because Cucable runs before the framework invocations
- You have full control over your runners because of template variables and custom placeholders

I agree that there might be more value for users with Cucumber < 4 but the above points may be valuable to Cucumber 4 users.
